### ISSUE TITLE
Anmälningsformulär

### ISSUE THREAD

**Issue by tradfursten** [day-of-the-programmer/day-of-the-programmer.github.io#1]

**Comment by buurd** [comment]
Nu finns det ett anmälningsformulär i vår mapp. Behöver sannolikt bearbetas lite :-)
Frågorna om man kollat med chefen är kontroller av att företaget faktiskt är intresserade och inte bara tomma förhoppningar.

**Comment by buurd** [comment]
Vi gör inte mer med denna!
