### ISSUE TITLE
Call for speakers / call for paper

### ISSUE THREAD

**Issue by tradfursten** [day-of-the-programmer/day-of-the-programmer.github.io#2]

**Comment by buurd** [comment]
Har du gjort något du vill berätta om? Då är en konferens ett bra ställe att berätta på. 

Vi har under två typer av föreläsningstyper. 
1) 45 minuters föreläsning. En sådan föreläsning tror vi är av lite mer allmän natur (inom programmeringen värld). Eftersom vi inte har några parallella spår under dessa spår är det bra om ämnet är relevant oavsett programmeringsspråk. Utgå från att en del av publiken inte har förkunskaper i ämnet. Viss ersättning utgår efter överenskommelse. 
2) 15 minuters föreläsning. Dessa kör vi i tre parallella spår så här kan man nörda in på specifika detaljer och förutsätta ganska specifika förkunskaper. Det är ett kortare format så se till att få in din poäng i tid. Ingen möjlighet att dra över eller ta frågor från publiken. Ersättning kan ges vid speciella förutsättningar (och sponsorpengar)

**Comment by EminaB** [comment]
"Vi har under två typer av föreläsningstyper" låter lite konstigt. 
Kanske: Vi kommer att fokusera på två föreläsningstyper 

I beskrivningen av 45 minuters föreläsningen skrivs det: tror vi är av lite mer allmänt natur. Är det inte bättre att skriva att det ska vara så och ta bort tror?

**Comment by buurd** [comment]
Denna är klar.
