### ISSUE TITLE
Vill du vara med och sponsra?

### ISSUE THREAD

**Issue by tradfursten** [day-of-the-programmer/day-of-the-programmer.github.io#3]
Vill ditt företag vara med och sammarbeta för att göra konferensen till en hejdundrandes grej?

**Comment by buurd** [comment]
En konferens händer inte av sig självt, utan det behövs pengar och tid för att det ska bli bra. Här har du ett tillfälle att både hjälpa till och samtidigt ge ditt företag en stund i rampljuset inför den publik du helst vill nå ut till! 
Skriv ett mail till sponsor@dayoftheprogrammer.se så kan vi påbörja utformningen av ditt företags engagemang i konferensen.

**Comment by buurd** [comment]
Vi gör inte  mer med denna i nuläget.
