### ISSUE TITLE
Information om vad det är

### ISSUE THREAD

**Issue by tradfursten** [day-of-the-programmer/day-of-the-programmer.github.io#4]
Vad är det för något ens?
Vars händer det?

**Comment by buurd** [comment]
Första utkast, för vidare diskusssion:

En konferens för programmerare, av programmerare och på dagen för programmerare. Bättre än så blir det inte! Fokus är alltså på att skapa och läsa kod och de verktyg som vi använder för att utföra dessa uppgifter.

Day of the programmer 2017 är en halvdagskonferens med intressanta föreläsningar för; och möten med andra; programmerare i Jönköping, knutpunkten dit man enkelt tar sig från Malmö, Göteborg eller Stockholm. 

Datum: 2017-09-13
Tid: 12:00 
Plats: Södra strandgatan 3

**Comment by tradfursten** [comment]
Jag började på något liknande denna text i mina skisser:

Varför är alla bra konferenser så långt bort? Denna fråga har vi ställt ossoch kommit fram till svaret: För att ingen har tagit tag i det i Jönköping.

Det finns många bra initiativ från olika företag. Tillexempel Divid Dojo, Jkpg Dojo, Jkpg JUG, Conside Code Summit. Men de har <nått om att bara ett företag bakom sig osv>.

**Comment by buurd** [comment]
Lite osäker på vad <nått om att bara ett företag bakom sig> tillför. Klippte ihop våra förslag..
<text>Varför är alla bra konferenser så långt bort? Denna fråga har vi ställt oss och kommit fram till svaret: För att ingen har tagit tag i det i Jönköping. Därför har vi bestämt oss för att starta en konferens i Jönköping. En konferens för programmerare, av programmerare och på dagen för programmerare. Bättre än så blir det inte! Fokus är alltså på att skapa och läsa kod och de verktyg som vi använder för att utföra dessa uppgifter.

Day of the programmer 2017 är en halvdagskonferens med intressanta föreläsningar för; och möten med andra; programmerare i Jönköping, knutpunkten dit man enkelt tar sig från Malmö, Göteborg eller Stockholm.

Datum: 2017-09-13
Tid: 12:00
Plats: Södra strandgatan 3cd 
</text>

**Comment by tradfursten** [comment]
Jag fastnade där i <> biten. Jag tyckte att Varför är alla bra konferenser så långt borta? Var en bra fråga att inleda med och hittade inte ett tydligt bra svar. Jag gillar din sätt att väva ihop det.

**Comment by buurd** [comment]
Vi gör inte mer med denna nu.
